use rohanuni;

DROP TABLE IF EXISTS Users;
CREATE TABLE Users (
	userID		BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	firstName	VARCHAR(50) NOT NULL,
	lastName	VARCHAR(50) NOT NULL,
	email		VARCHAR(100) NOT NULL,
	password	VARCHAR(255) DEFAULT NULL,
	address		VARCHAR(255) DEFAULT NULL,
	phone		VARCHAR(30) NOT NULL,
	enabled		BOOLEAN DEFAULT FALSE,
	nonLocked	BOOLEAN DEFAULT TRUE,
	usingMFA	BOOLEAN DEFAULT FALSE,
	createdAt	DATATIME DEFAULT CURRENT_TIMESTAMP,
	imageURL	VARCHAR(255) DEFAULT 'https://cdn-icons-png.flaticon.com/512/149/149071.png'
);

DROP TABLE IF EXISTS Roles;
CREATE TABLE Roles (
	roleID		BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name		VARCHAR(50) NOT NULL UNIQUE,
	perms		VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS UserRoles;
CREATE TABLE UserRoles (
	userRoleID		BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	userID			BIGINT UNSIGNED NOT NULL,
	roleID			BIGINT UNSIGNED NOT NULL,
	
	CONSTRAINT Users_UserRoles_fk FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT Roles_UserRoles_fk FOREIGN KEY (roleID) REFERENCES Roles(roleID) ON DELETE RESTRICT ON UPDATE CASCADE
);

DROP TABLE IF EXISTS Events;
CREATE TABLE Events (
	eventID		BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`type`		VARCHAR(50) NOT NULL UNIQUE CHECK(type IN ('LOGIN_ATTEMPT', 'LOGIN_ATTEMPT_FAILURE', 'LOGIN_ATTEMPT_SUCCESS', 'PROFILE_UPDATE', 'PROFILE_PRICTURE_UPDATE', 'PASSWORD_UPDATE', 'MFA_UPDATE')),
	description	VARCHAR(255) DEFAULT NULL
);

DROP TABLE IF EXISTS user_events;
CREATE TABLE user_events (
	userEventID		BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	userID			BIGINT UNSIGNED NOT NULL,
	eventID			BIGINT UNSIGNED NOT NULL,
	device			VARCHAR(100) DEFAULT NULL,
	ip_addr			VARCHAR(100) DEFAULT NULL,
	createdAt		DATETIME DEFAULT CURRENT_TIMESTAMP,
	
	CONSTRAINT Users_user_events_fk FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT Events_user_events_fk FOREIGN KEY (eventID) REFERENCES Events(eventID) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS AccountVerifications;
CREATE TABLE AccountVerifications (
	accVerID		BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	userID			BIGINT UNSIGNED NOT NULL UNIQUE,
	url				VARCHAR(255) NOT NULL UNIQUE,
	expiryDate		DATETIME NOT NULL,
	resetURL		VARCHAR(255) NOT NULL UNIQUE,
	
	CONSTRAINT Users_AccountVerifications_fk FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE
);

DROP TABLE IF EXISTS MultiFactorVerifications;
CREATE TABLE MultiFactorVerifications (
	mfaID			BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	userID			BIGINT UNSIGNED NOT NULL UNIQUE,
	code			VARCHAR(10) NOT NULL UNIQUE,
	expiryDate		DATETIME NOT NULL,
	resetURL		VARCHAR(255) NOT NULL UNIQUE,
	
	CONSTRAINT Users_MultiFactorVerifications_fk FOREIGN KEY (userID) REFERENCES Users(userID) ON DELETE CASCADE ON UPDATE CASCADE
);


DROP TABLE IF EXISTS Courses;
CREATE TABLE Courses (
  courseID 		INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  courseName 	varchar(20) NOT NULL
);

DROP TABLE IF EXISTS Students;
CREATE TABLE Students (
  rollNo 		INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  studentName 	varchar(20) NOT NULL,
  age 			INT NOT NULL
);

DROP TABLE IF EXISTS students_courses;
CREATE TABLE IF NOT EXISTS students_courses (
  rollNo 	INT UNSIGNED NOT NULL,
  courseID 	INT UNSIGNED NOT NULL,
  
  CONSTRAINT Students_students_courses_fk FOREIGN KEY (rollNo) REFERENCES Students(rollNo),
  CONSTRAINT Courses_students_courses_fk FOREIGN KEY (courseID) REFERENCES Courses(courseID)
);